### PR TITLE
release 3.0.1

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Do we really need a release for this? Looks to me like all changes don't affect actual users.

**Comment by bastelfreak** [comment]
My idea was to publish all of the puppet-lint plugins again so we've them as github packages. Also some gems had wrong attributes in the gemspec file so that would be corrected as well. If you like I can only publish the lint plugins with changes.

**Comment by ekohl** [comment]
Shouldn't this at most be a patch release then?

**Comment by bastelfreak** [comment]
updated it to a patch release

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
OK to me since you can argue that the badges should be shown correctly on Rubygems.

**Pull request merged**
